# Generated by Django 5.2.6 on 2025-10-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0005_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='important_note',
            field=models.TextField(blank=True, default='', verbose_name='Important Note'),
        ),
    ]
