# Generated by Django 5.2.6 on 2025-10-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0006_shop_important_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='important_note',
        ),
        migrations.AddField(
            model_name='shop',
            name='payment_phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Online Payment Phone'),
        ),
    ]
