# Generated by Django 5.2.6 on 2025-10-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0008_shop_latitude_shop_longitude_alter_shop_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='longitude',
        ),
        migrations.AddField(
            model_name='order',
            name='notified_to_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.TextField(),
        ),
    ]
