# Generated by Django 5.2.6 on 2025-10-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0009_remove_shop_latitude_remove_shop_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
