# Generated by Django 5.2.7 on 2025-10-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0012_shop_latitude_shop_longitude_alter_shop_shop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='longitude',
        ),
    ]
