# Generated by Django 5.2.7 on 2025-10-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0013_remove_shop_latitude_remove_shop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
