# Generated by Django 5.2.7 on 2025-10-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0016_shop_latitude_shop_longitude_user_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
    ]
