# Generated by Django 5.2.7 on 2025-10-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0018_shop_latitude_shop_longitude_user_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
