# Generated by Django 5.2.7 on 2025-10-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0019_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
