# Generated by Django 5.2.7 on 2025-10-23 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0021_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='mart.order'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.TextField(blank=True, help_text="Customer's address/area", null=True),
        ),
    ]
